version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8  # Wybierz wersję Pythona, której używasz

    steps:
      - checkout  # Klonuje repozytorium
      - run:
          name: "Install dependencies"
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt  # Upewnij się, że masz plik requirements.txt
      - run:
          name: "Run unit tests"
          command: |
            python -m unittest discover -s . -p "test_kalkulator2.py"  # Uruchamia testy jednostkowe

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
