version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8 

    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: "Run unit tests"
          command: |
            python -m unittest discover -s . -p "test_kalkulator2.py"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
