<<<<<<< HEAD
=======
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests from test_kalkulator2.py
          command: |
            . venv/bin/activate
            python -m unittest discover -s . -p "test_kalkulator2.py"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
>>>>>>> 8eddabe749f9a2428f5a7a4f901e10ee7e794bcc
