version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Set up virtual environment
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt  # Instalacja zależności
      - run:
          name: Run tests using unittest
          command: |
            . venv/bin/activate
            python -m unittest discover -s . -p "*.py"

workflows:
  version: 2
  test:
    jobs:
      - test
